on:
  # release:
  #   types: [published]
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set tag
        id: set_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}

      # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - run: npm install
        working-directory: ./packages/core
      - run: npm run build:babel
        working-directory: ./packages/core
      - run: npm publish --access public
        working-directory: ./packages/core
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
