on:
  # release:
  #   types: [published]
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set tag
        id: set_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
        working-directory: ./packages/core
      - run: npm run build:babel
        working-directory: ./packages/core
      - run: npm publish --access public
        working-directory: ./packages/core
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
